### ISSUE TITLE
When launching this URL: https://<notmynumber>trial-dev-theta-app.cfapps.us10.hana.ondemand.com/trustee/get-account2

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/btp-blockchain-theta#2]
i keep getting _Gateway Timeout_ message and the following entries in the trial account log:

```
2021-05-20T11:50:45.599+0000 [APP/PROC/WEB/0] ERR (node:133) UnhandledPromiseRejectionWarning: Error: Account with address 0x0[notmynumber] is not found
2021-05-20T11:50:45.599+0000 [APP/PROC/WEB/0] ERR at getResult (/home/vcap/deps/0/node_modules/@thetalabs/theta-js/dist/thetajs.cjs.js:1091:23)
2021-05-20T11:50:45.599+0000 [APP/PROC/WEB/0] ERR at HttpProvider.send (/home/vcap/deps/0/node_modules/@thetalabs/theta-js/dist/thetajs.cjs.js:1190:16)
2021-05-20T11:50:45.599+0000 [APP/PROC/WEB/0] ERR at process._tickCallback (internal/process/next_tick.js:68:7)
2021-05-20T11:50:45.600+0000 [APP/PROC/WEB/0] ERR (node:133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```

Thank you,
greg

**Comment by greg2git** [comment]
actually, i needed the hardcoded value from the server.js file entered into the credential service in BTP:

`https://github.com/SAP-samples/btp-blockchain-theta/blob/168a30e6d68bcb91422a2b63dc150f7a3c418c83/cf/trustee/server.js#L39`

Thanks,
gm
